@startuml
!theme mars
skinparam stateFontSize 20
skinparam arrowFontSize 14
state "Монетоприемник (A1)" as A1 {
    [*] --> A10
    state "Монетоприемник пуст" as A10 : 
    state "Монетоприемник закрыт" as A13 : 
    state "Жетон принят" as A11 : <size:14>A0(e11)
    state "Жетон не распознан" as A12 : <size:14>A0(e11)
    A10 --> A11 : <u>e10 & x11 & y3!=1\nz12,z30,z31
    A10 --> A12 : <u>e10 & !x11 & y3!=1\nz12
    A11 --> A11 : <u>e10 & x11 & y3!=1\nz12,z30,z31
    A11 --> A10 : <u>A0(e02)\nz14
    A11 --> A13 : <u>A0(e12)\nz02,z16,z15
    A11 --> A12 : <u>e10 & !x11 & y3!=1\nz12
    A12 --> A10 : <u>A0(e02)\nz14
    A13 --> A10 : <u>A0(e14)\n~
}
@enduml
