@startuml
skinparam backgroundColor white
state "Игровая машина x Монетоприемник x Игровые барабаны x Джекпот-счётчик x Звуки (A0A1A2A3A4)" as A0A1A2A3A4 {
    [*] --> A0A1A2A3A421
    state "Ожидание * Монетоприемник пуст * Барабаны остановлены * Накопление * Ожидание" as A0A1A2A3A421 : <size:14>z03,z13,z12
    state "Прием жетонов * Жетон принят * Барабаны остановлены * Накопление * Ожидание" as A0A1A2A3A45 : 
    state "Ошибка * Жетон не распознан * Барабаны остановлены * Накопление * Ожидание" as A0A1A2A3A46 : 
    state "Игра * Монетоприемник закрыт * Барабаны запущены * Накопление * Ожидание" as A0A1A2A3A49 : 
    state "Игра * Монетоприемник закрыт * Первый барабан остановлен * Накопление * Ожидание" as A0A1A2A3A48 : 
    state "Игра * Монетоприемник закрыт * Второй барабан остановлен * Накопление * Ожидание" as A0A1A2A3A410 : 
    state "Выдача жетона * Монетоприемник закрыт * Барабаны остановлены * Выплата джекпота * Ожидание" as A0A1A2A3A415 : 
    state "Выдача жетона * Монетоприемник закрыт * Барабаны остановлены * Накопление * Ожидание" as A0A1A2A3A418 : 
    state "Ошибка * Монетоприемник закрыт * Барабаны остановлены * Накопление * Ожидание" as A0A1A2A3A419 : 
    A0A1A2A3A421 --> A0A1A2A3A45 : <u>e10 & x11\nz12,z30,z31
    A0A1A2A3A421 --> A0A1A2A3A46 : <u>e10 & !x11\nz12,z02
    A0A1A2A3A45 --> A0A1A2A3A421 : <u>d02\nz02,z14
    A0A1A2A3A45 --> A0A1A2A3A49 : <u>e01\nz02,z16,z15,z20
    A0A1A2A3A45 --> A0A1A2A3A45 : <u>e10 & x11\nz12,z30,z31
    A0A1A2A3A45 --> A0A1A2A3A46 : <u>e10 & !x11\nz12,z02
    A0A1A2A3A46 --> A0A1A2A3A421 : <u>d02\nz14
    A0A1A2A3A49 --> A0A1A2A3A48 : <u>e22\nz23
    A0A1A2A3A49 --> A0A1A2A3A49 : <u>e01\nz21
    A0A1A2A3A48 --> A0A1A2A3A410 : <u>e23\nz25
    A0A1A2A3A410 --> A0A1A2A3A415 : <u>e05 & x30 & x01 & x02\nz31,z27,z28,z04
    A0A1A2A3A410 --> A0A1A2A3A415 : <u>e05 & x30 & !x01\nz31,z27,z28
    A0A1A2A3A410 --> A0A1A2A3A418 : <u>e05 & !x30 & x01 & x02\nz27,z28,z04
    A0A1A2A3A410 --> A0A1A2A3A421 : <u>e05 & !x30 & !x01\nz27,z28
    A0A1A2A3A415 --> A0A1A2A3A415 : <u>e06 & x01 & x02\nz40,z04,z28,z15
    A0A1A2A3A415 --> A0A1A2A3A419 : <u>e06 & x01 & !x02\nz40,z28,z15,z32,z31
    A0A1A2A3A415 --> A0A1A2A3A421 : <u>e06 & !x01\nz40,z28,z15,z32,z31
    A0A1A2A3A418 --> A0A1A2A3A418 : <u>e06 & x01 & x02\nz40,z04,z28,z15
    A0A1A2A3A418 --> A0A1A2A3A419 : <u>e06 & x01 & !x02\nz40,z28,z15
    A0A1A2A3A418 --> A0A1A2A3A421 : <u>e06 & !x01\nz40,z28,z15
    A0A1A2A3A419 --> A0A1A2A3A421 : <u>e03\nz05,z28,z15
}
@enduml
