@startuml
skinparam backgroundColor white
state "Игровая машина x Монетоприемник x Игровые барабаны x Джекпот-счётчик (A0A1A2A3)" as A0A1A2A3 {
    [*] --> A0A1A2A321
    state "Ожидание * Монетоприемник пуст * Барабаны остановлены * Накопление" as A0A1A2A321 :  z03,z13,z12
    state "Прием жетонов * Жетон принят * Барабаны остановлены * Накопление" as A0A1A2A35 :  
    state "Ошибка * Жетон не распознан * Барабаны остановлены * Накопление" as A0A1A2A36 :  
    state "Игра * Монетоприемник закрыт * Барабаны запущены * Накопление" as A0A1A2A39 :  
    state "Игра * Монетоприемник закрыт * Первый барабан остановлен * Накопление" as A0A1A2A38 :  
    state "Игра * Монетоприемник закрыт * Второй барабан остановлен * Накопление" as A0A1A2A310 :  
    state "Выдача жетона * Монетоприемник закрыт * Барабаны остановлены * Выплата джекпота" as A0A1A2A315 :  
    state "Выдача жетона * Монетоприемник закрыт * Барабаны остановлены * Накопление" as A0A1A2A318 :  
    state "Ошибка * Монетоприемник закрыт * Барабаны остановлены * Накопление" as A0A1A2A319 :  
    A0A1A2A321 --> A0A1A2A35 : <u>e10 & x11\nz12,z30,z31
    A0A1A2A321 --> A0A1A2A36 : <u>e10 & !x11\nz12,z02
    A0A1A2A35 --> A0A1A2A321 : <u>d02\nz02,z14
    A0A1A2A35 --> A0A1A2A39 : <u>e01\nz02,z16,z15,z20
    A0A1A2A35 --> A0A1A2A35 : <u>e10 & x11\nz12,z30,z31
    A0A1A2A35 --> A0A1A2A36 : <u>e10 & !x11\nz12,z02
    A0A1A2A36 --> A0A1A2A321 : <u>d02\nz14
    A0A1A2A39 --> A0A1A2A38 : <u>e22\nz23
    A0A1A2A39 --> A0A1A2A39 : <u>e01\nz21
    A0A1A2A38 --> A0A1A2A310 : <u>e23\nz25
    A0A1A2A310 --> A0A1A2A315 : <u>e05 & x30 & x01 & x02\nz31,z27,z28,z04
    A0A1A2A310 --> A0A1A2A315 : <u>e05 & x30 & !x01\nz31,z27,z28
    A0A1A2A310 --> A0A1A2A318 : <u>e05 & !x30 & x01 & x02\nz27,z28,z04
    A0A1A2A310 --> A0A1A2A321 : <u>e05 & !x30 & !x01\nz27,z28
    A0A1A2A315 --> A0A1A2A315 : <u>e06 & x01 & x02\nz04,z28,z15
    A0A1A2A315 --> A0A1A2A319 : <u>e06 & x01 & !x02\nz28,z15,z32,z31
    A0A1A2A315 --> A0A1A2A321 : <u>e06 & !x01\nz28,z15,z32,z31
    A0A1A2A318 --> A0A1A2A318 : <u>e06 & x01 & x02\nz04,z28,z15
    A0A1A2A318 --> A0A1A2A319 : <u>e06 & x01 & !x02\nz28,z15
    A0A1A2A318 --> A0A1A2A321 : <u>e06 & !x01\nz28,z15
    A0A1A2A319 --> A0A1A2A321 : <u>e03\nz05,z28,z15
}
@enduml
