object GameIncorrect {
    fun buildA2() = AutomatonBuilder("Игровые барабаны", listOf("A2"))
        .environmentEvent("e23", "Сработал таймер второго барабана")
        .environmentEvent("e22", "Сработал таймер первого барабана")
        .environmentEvent("z20", "Запустить барабаны")
        .environmentEvent("z21", "Запустить таймер первого барабана")
        .environmentEvent("z23", "Запустить таймер второго барабана")
        .environmentEvent("z25", "Запустить таймер третьего барабана")
        .environmentEvent("z27", "Установить сумму выигрыша")
        .environmentEvent("z28", "Обновить индикатор «Выигрыш»")
        .automationEvent("a0", "A0", "Начало игры")
        .automationEvent("e01", "A0", "Нажата кнопка «Игра»")
        .automationEvent("e05", "A0", "Сработал таймер третьего барабана")
        .state(0, "Барабаны остановлены")
        .state(1, "Барабаны запущены")
        .state(2, "Первый барабан остановлен", listOf("z23"))
        .state(3, "Второй барабан остановлен", listOf("z25"))
        .transition(0, 1, "a0", enterEventsId = listOf("z20"))
        .transition(1, 1, "e01", enterEventsId = listOf("z21"))
        .transition(1, 2, "e22")
        .transition(2, 3, "e23")
        .transition(3, 0, "e05", enterEventsId = listOf("z27", "z28"))
        .build()

    fun buildA0() = AutomatonBuilder("Игровая машина", listOf("A0"))
        .automationEvent("a0", "A2", "Начало игры")
        .automationEvent("a11", "A1", "Опущен жетон")
        .environmentEvent("e01", "Нажата кнопка «Игра»")
        .environmentEvent("e02", "Нажата кнопка «Возврат»")
        .environmentEvent("e03", "Нажата кнопка «Тех. сброс»")
        .environmentEvent("e05", "Сработал таймер третьего барабана")
        .environmentEvent("e06", "Выдан жетон из банка")
        .environmentEvent("z02", "Закрыть монетоприемник")
        .environmentEvent("z03", "Открыть монетоприемник")
        .environmentEvent("z04", "Выдать жетон из банка")
        .environmentEvent("z05", "Сбросить сумму выигрыша")
        .environmentEvent("z12", "Обновить индикатор «Ставка»")
        .environmentEvent("z13", "Сбросить ставку")
        .environmentEvent("z15", "Обновить индикатор «Банк»")
        .environmentEvent("z28", "Обновить индикатор «Выигрыш»")
        .environmentEvent("x01", "Cумма выдачи выигрыша больше нуля")
        .environmentEvent("x02", "В банке есть жетоны")
        .environmentEvent("!x01", "!Cумма выдачи выигрыша больше нуля")
        .environmentEvent("!x02", "!В банке есть жетоны")
        .automationEvent("a02", "A1", "Нажата кнопка «Возврат»")
        .automationEvent("a12", "A1", "Необходимо перевести жетоны в банк")
        .automationStateEvent("y1", "A1", "Жетон принят", 1)
        .automationStateEvent("y2", "A1", "Жетон не распознан", 2)
        .automationStateEvent("y3", "A1", "y1!=2", 2, false)
        .state(0, "Ожидание", listOf("z03", "z13", "z12"))
        .state(1, "Прием жетонов")
        .state(2, "Игра", listOf("a0"), nestedFsmIds = listOf("A2"))
        .state(3, "Ошибка")
        .state(4, "Выдача жетона")
// 0
        .transition(0, 1, "a11", listOf("y1"))
        .transition(0, 3, "a11", listOf("y2"), listOf("z02"))
// 1
        .transition(1, 0, "e02", listOf(), listOf("z02", "a02"))
        .transition(1, 2, "e01", listOf("y1"), listOf("a12"))
        .transition(1, 3, "a11", listOf("y2"), listOf("z02"))
// 2
        .transition(2, 4, "e05", listOf("x01", "x02"), listOf("z04")) //listOf("x01", "x02"),
        .transition(2, 0, "e05", listOf("!x01"))
// 3
        .transition(3, 0, "e03", listOf("y3"), listOf("z05", "z28", "z15"))
        .transition(3, 0, "e02", listOf("y2"), listOf("a02"))
// 4
        .transition(4, 4, "e06", listOf("x01", "x02"), listOf("z04", "z28", "z15"))
        .transition(4, 3, "e06", listOf("x01", "!x02"), listOf("z28", "z15"))
        .transition(4, 0, "e06", listOf("!x01"), enterEventsId = listOf("z28", "z15"))
        .build()

    fun buildA1() = AutomatonBuilder("Монетоприемник", listOf("A1"))
        .automationEvent("a02", "A0", "Нажата кнопка «Возврат»")
        .automationEvent("a11", "A0", "Опущен жетон")
        .automationEvent("a12", "A0", "Необходимо перевести жетоны в банк")
        .automationEvent("f02", "A0", "Закрыть монетоприемник")
        .automationEvent("f03", "A0", "Открыть монетоприемник")
        .environmentEvent("e10", "Опущен жетон")
        .environmentEvent("z02", "Закрыть монетоприемник")
        .environmentEvent("z12", "Обновить индикатор «Ставка»")
        .environmentEvent("z31", "Поместить жетоны в банк")
        .environmentEvent("z14", "Вернуть деньги")
        .environmentEvent("z15", "Обновить индикатор «Банк»")
        .environmentEvent("x11", "Жетон подлинный")
        .environmentEvent("x12", "Жетон не подлинный")

        .state(0, "Монетоприемник пуст")
        .state(1, "Жетон принят", listOf("a11"))
        .state(2, "Жетон не распознан", listOf("a11"))
        .transition(0, 1, "e10", listOf("x11"), listOf("z12"))
        .transition(0, 2, "e10", listOf("x12"), listOf("z12"))
// 1
        .transition(1, 1, "e10", listOf("x11"), listOf("z12"))
        .transition(1, 0, "a02", enterEventsId = listOf("z14"))
        .transition(1, 0, "a12", enterEventsId = listOf("z02", "z31", "z15"))
        .transition(1, 2, "e10", listOf("x12"), listOf("z12"))
// 2
        .transition(2, 0, "a02", enterEventsId = listOf("z14"))
        .build()
}


fun main() {
    val a0 = GameIncorrect.buildA0()
    val a1 = GameIncorrect.buildA1()
    val a2 = GameIncorrect.buildA2()

//    Corrector(a0, a2).correct()

    var res = Multiplier(a0, a1).multiply()
//    res = Multiplier(res, a2).multiply()

    println()
    println(a0.toUML())

    println()
    println(a1.toUML())

    println()
    println(a2.toUML())
//
    println()
    println(res.toUML())

    println(res.states.count())
    println(res.transitions.count())
}
